animal = input("There once was a(n) [animal] ")
adjective = input ("The " + animal + "was very [adjective] ")
verb = input ("The " + animal + " spent it's days [verb] ")
noun = input ("One day the " + animal + " found a [noun] ")
verb2 = input ("The " + animal + "'s newfound " + noun + " was [verb in past tense] ")
verb3 = input ("The " + animal + "had to [verb] " + " it.")
noun2 = input ("The " + animal + " decided, this would be it's new [noun] ")
verb4 = input ("the " + animal + " decided to [verb] ")
adjective = input ("and lived [adjective] ")
print ("ever after!")
